Blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'', include('blogs.urls', namespace='blogs')),
    re_path(r'^users/', include('users.urls', namespace='users')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_name = 'Blog'

blogs/urls.py
from django.urls import path, re_path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Домашняя страница. Вывод всех публичных постов.
    re_path(r'^$', views.public_posts,
        name='index'),

    # Страница для добавления нового поста
    re_path(r'^new_post/$', views.new_post,
        name='new_post'),

    # Страница для редактирования записи
    re_path(r'^edit_post/(?P<post_id>\d+)/$', views.edit_post,
        name='edit_post'),

    # Удаление поста
    re_path(r'^delete_post/(?P<post_id>\d+)/$', views.delete_post,
        name='delete_post'),

    # Страница с личными публикациями
    re_path(r'^owner_posts/$', views.owner_posts,
        name='owner_posts'),

    # Страница для отельного поста
    re_path(r'^post_details/(?P<post_id>\d+)/$', views.post_details,
        name='post_details'),

    # Публикация/приватизация поста
    re_path(r'^privat_public/(?P<post_id>\d+)/$', views.privat_public,
        name='privat_public'),

    # Страница для добавления нового tag
    re_path(r'^new_tag/$', views.new_tag,
        name='new_tag'),

    # Введет все посты, прикрепленные к этому тегу
    re_path(r'^tag_detail/(?P<tag_id>\d+)/$', views.tag_detail, name='tag_detail'),

    # Удаление поста
    re_path(r'^delete_tag/(?P<tag_id>\d+)/$', views.delete_tag,
        name='delete_tag'),

]
app_name = 'blogs'

users/urls.py
"""Определяет схемы URL для пользователей"""
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path, include
from django.urls import path
from . import views

urlpatterns = [
    re_path('login/', LoginView.as_view(template_name='users/login.html'),
         name="login"),
    re_path(r'^logout/$', views.logout_view, name='logout'),
    # Страница регистрации
    re_path(r'^register/$', views.register, name='register'),
]

app_name = "users"

blogs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=130)
    text = models.TextField()
    image = models.ImageField(null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_edit = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    public = models.BooleanField(default=False)
    date_publication = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField('Tag', blank=True, related_name='posts')

    def __str__(self):
        return self.title + ":\n" + self.text

    class Meta:
        ordering = ['-date_added']


class Tag(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.title)

blogs/forms.py
from django import forms
from .models import BlogPost, Tag
from django.forms.widgets import ClearableFileInput


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text', 'image', 'public', 'tags']
        labels = {'title': '', 'text': ''}
        widgets = {'title': forms.Textarea(attrs={'cols': 80, 'rows': 1}),
                   'text': forms.Textarea(attrs={'cols': 80})}


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['title']
        labels = {'title': ''}
        widgets = {'title': forms.Textarea(attrs={'cols': 80, 'rows': 1})}

blogs/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogPost, Tag
from .forms import BlogPostForm, TagForm
from django.urls import reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404, HttpResponseNotFound
import datetime


# Create your views here.
@login_required
def owner_posts(request):
    """Страница My posts приложения Blog выводит список постов владельца"""
    owner_posts = BlogPost.objects.filter(owner=request.user).order_by('-date_added')
    paginator = Paginator(owner_posts, 12)
    page_number = request.GET.get('page', 1)
    owner_page = paginator.get_page(page_number)

    if owner_page.has_next():
        next_url = f'?page={owner_page.next_page_number()}'
    else:
        next_url = ''
    if owner_page.has_previous():
        prev_url = f'?page={owner_page.previous_page_number()}'
    else:
        prev_url = ''

    context = {'owner_page': owner_page,
               'owner_posts': owner_posts,
               'next_owner_page_url': next_url,
               'prev_owner_page_url': prev_url}
    return render(request, 'blogs/my_posts.html', context)


def public_posts(request):
    """Выводит список публичных тем на главной странице"""
    public_posts = BlogPost.objects.filter(public=True).order_by('-date_added')
    paginator = Paginator(public_posts, 10)
    page_number = request.GET.get('page', 1)
    public_page = paginator.get_page(page_number)

    if public_page.has_next():
        next_url = f'?page={public_page.next_page_number()}'
    else:
        next_url = ''
    if public_page.has_previous():
        prev_url = f'?page={public_page.previous_page_number()}'
    else:
        prev_url = ''

    context = {'public_page': public_page,
               'public_posts': public_posts,
               'next_public_page_url': next_url,
               'prev_public_page_url': prev_url}
    return render(request, 'blogs/index.html', context)


@login_required
def new_post(request):
    """Добавляет новый пост."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = BlogPostForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = BlogPostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            form.save_m2m()
            if new_post.public:
                return HttpResponseRedirect(reverse('blogs:index'))
            else:
                return HttpResponseRedirect(reverse('blogs:owner_posts'))
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)


@login_required
def edit_post(request, post_id):
    """Редактирует существующий пост."""
    post = get_object_or_404(BlogPost, id=post_id)
    if post.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = BlogPostForm(instance=post)
    else:
        # Отправка данных POST; обработать данные.
        form = BlogPostForm(instance=post, data=request.POST, files=request.FILES)
        if form.is_valid():
            post.date_edit = datetime.datetime.now()
            form.save()
        return HttpResponseRedirect(reverse('blogs:owner_posts'))

    context = {'post': post, 'form': form}
    return render(request, 'blogs/edit_post.html', context)


def post_details(request, post_id):
    """Выводит пост целиком"""
    post = get_object_or_404(BlogPost, id=post_id)
    if post.owner != request.user and post.public != True:
        raise Http404

    context = {'post': post}
    return render(request, 'blogs/post_details.html', context)


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(BlogPost, id=post_id)
    if post.owner != request.user:
        raise Http404
    post.delete()
    return HttpResponseRedirect(reverse('blogs:owner_posts'))


@login_required
def privat_public(request, post_id):
    """Публикует/скрывает пост"""
    post = get_object_or_404(BlogPost, id=post_id)
    if post.owner != request.user:
        raise Http404
    if post.public:
        post.public = False
    else:
        post.public = True
        post.date_publication = datetime.datetime.now()
    post.save()
    if post.public:
        return HttpResponseRedirect(reverse('blogs:index'))
    else:
        return HttpResponseRedirect(reverse('blogs:owner_posts'))


def tag_detail(request, tag_id):
    """Выводит список постов по заданому тегу"""
    tag = get_object_or_404(Tag, id=tag_id)
    tag_posts = tag.posts.all()
    paginator = Paginator(tag_posts, 10)
    page_number = request.GET.get('page', 1)
    tag_page = paginator.get_page(page_number)

    if tag_page.has_next():
        next_url = f'?page={tag_page.next_page_number()}'
    else:
        next_url = ''
    if tag_page.has_previous():
        prev_url = f'?page={tag_page.previous_page_number()}'
    else:
        prev_url = ''

    context = {'tag': tag,
               'tag_page': tag_page,
               'tag_posts': tag_posts,
               'next_tag_page_url': next_url,
               'prev_tag_page_url': prev_url}
    return render(request, 'blogs/tag_detail.html', context)


@login_required
def new_tag(request):
    """Добавляет новый пост."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = TagForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:new_tag'))
    context = {'form': form}
    return render(request, 'blogs/new_tag.html', context)


@login_required
def delete_tag(request, tag_id):
    tag = get_object_or_404(Tag, id=tag_id)
    tag.delete()
    return HttpResponseRedirect(reverse('blogs:new_tag'))

blogs/templates/blogs/base.html
{% load bootstrap4 %}
{% load static %}

<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Blog</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blogs:index' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07"
                aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        <div class="collapse navbar-collapse" id="navbarsExample07">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'blogs:owner_posts' %}">My posts</a>
                </li>
                <div class="pl-2">
                    <li class="nav-item">
                        <a href="{% url 'blogs:new_post' %}" class="btn btn-outline-light" role="button">Add Post</a>
                    </li>
                </div>
                <div class="pl-2">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Tags</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown01">
                            <div class="pl-2">
                                <a href="{% url 'blogs:new_tag' %}" class="btn btn-outline-dark" role="button">Add/Delete
                                    Tag</a>
                            </div>
                            {% for tag in tags %}
                            <a class="dropdown-item" href="{% url 'blogs:tag_detail' tag.id %}">{{ tag.title }}</a>
                            {% endfor %}
                        </div>
                </div>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav justify-content-end">
                {% if user.is_authenticated %}
                <div class="pr-2">
                <span class="navbar-text">
                Hello, {{ user.username }}.
              </span>
                </div>
                <div class="pr-2">
                    <li><a class="nav-link" href="{% url 'users:logout' %}">Log out</a></li>
                </div>
                <li><a class="nav-link" href="{% url 'admin:index' %}">Admin panel</a></li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</div>

</body>
</html>

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block header %}
<div class="p-2">
    <h4 align="center">Edit post</h4>
</div>
{% endblock header %}

{% block content %}

<form action="{% url 'blogs:edit_post' post.id %}" class="form" enctype="multipart/form-data"
      method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-dark">Save changes</button>
    {% endbuttons %}
</form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}
{% block header %}

<div class="pt-2">
    <h2 align="center">Public Posts</h2>
</div>
{% endblock header %}

{% block content %}

<div class="card-group">
    {% for post in public_page.object_list %}

    <div class="col-md-6 p-2">
        <div class="card">
            {% if post.image %}
            <img src="{{ post.image.url }}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ post.title|linebreaks }}</h5>
                {% if post.text|length > 500 %}
                <p class="text-justify">{{ post.text|truncatechars:500 }}</p>
                {% else %}
                <p class="text-justify">{{ post.text|linebreaks }}</p>
                {% endif %}
                <div class="pb-3">
                    Tags:
                    {% for tag in post.tags.all %}
                    <a href="{% url 'blogs:tag_detail' tag.id %}">
                        #{{ tag.title }}
                    </a>
                    {% empty %}
                    none
                    {% endfor %}
                </div>
                <p><a href="{% url 'blogs:post_details' post.id %}" class="btn btn-outline-dark btn-block"
                      role="button">Read</a></p>
                <div class="card-footer">
                    <div class="float-right">Author: {{ post.owner }}</div>
                    <small class="text-muted">{{ post.date_added|date:'M d, Y H:i' }} Create</small>
                    <br><small class="text-muted">{{ post.date_edit|date:'M d, Y H:i' }} Edit</small></br>
                    <small class="text-muted">{{ post.date_publication|date:'M d, Y H:i' }} Published</small>
                </div>
            </div>
        </div>

    </div>
    {% empty %}
    No posts have been added yet.
    {% endfor %}
</div>

{% if public_posts|length > 10 %}
<nav aria-label="Search results pages">
    <ul class="pagination">
        <li class="page-item {% if not prev_public_page_url %} disabled {% endif %}">
            <a class="page-link" href="{{ prev_public_page_url }}" tabindex="-1" aria-disabled="true">Previous</a>
        </li>

        {% for n in public_page.paginator.page_range %}
        {% if public_page.number == n %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ n }}">{{ n }}<span class="sr-only">(current)</span></a>
        </li>
        {% elif n > public_page.number|add:-3 and n < public_page.number|add:3 %}
        <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
        {% endif %}
        {% endfor %}

        <li class="page-item {% if not next_public_page_url %} disabled {% endif %}">
            <a class="page-link" href="{{ next_public_page_url }}">Next</a>
        </li>
    </ul>
</nav>
{% endif %}
{% endblock content %}

blogs/templates/blogs/my_posts.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}
{% block header %}
<div class="pt-2">
    <h2 align="center">My Posts</h2>
</div>
{% endblock header %}

{% block content %}

<div class="card-group">
    {% for post in owner_page.object_list %}
    <div class="col-md-4 p-2">
        <div class="card">
            {% if post.image %}
            <img src="{{ post.image.url }}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                {% if post.public %}
                <h5>{{ post.title|linebreaks }}
                    <a href="{% url 'blogs:privat_public' post.id %}"
                       class="badge badge-success">Public</a></h5>
                {% else %}
                <h5>
                    {{ post.title|linebreaks }}
                    <a href="{% url 'blogs:privat_public' post.id %}" class="badge badge-dark">Private</a>
                </h5>
                {% endif %}
                {% if post.text|length > 300 %}
                <p class="text-justify">{{ post.text|truncatechars:300 }}</p>
                {% else %}
                <p class="text-justify">{{ post.text|linebreaks }}</p>
                {% endif %}
                <div class="pb-3">
                    Tags:
                    {% for tag in post.tags.all %}
                    <a href="{% url 'blogs:tag_detail' tag.id %}">
                        #{{ tag.title }}
                    </a>
                    {% empty %}
                    none
                    {% endfor %}
                </div>
                <p><a href="{% url 'blogs:post_details' post.id %}" class="btn btn-outline-dark btn-block"
                      role="button">Read</a></p>
                <a href="{% url 'blogs:edit_post' post.id %}" class="btn btn-outline-dark" role="button">Edit</a>
                <div class="float-right">
                    <a href="{% url 'blogs:delete_post' post.id %}" class="btn btn-outline-danger"
                       role="button">Delete</a>
                </div>

                <p></p>
                <div class="card-footer">
                    <div class="float-right">Author: {{ post.owner }}</div>
                    <small class="text-muted">{{ post.date_added|date:'M d, Y H:i' }} Create</small>
                    <br><small class="text-muted">{{ post.date_edit|date:'M d, Y H:i' }} Edit</small></br>
                    {% if post.public %}
                    <small class="text-muted">{{ post.date_publication|date:'M d, Y H:i' }} Published</small>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    No posts have been added yet.
    {% endfor %}
</div>

{% if owner_posts|length > 12 %}
<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item {% if not prev_owner_page_url %} disabled {% endif %}">
            <a class="page-link" href="{{ prev_owner_page_url }}" tabindex="-1" aria-disabled="true">Previous</a>
        </li>

        {% for n in owner_page.paginator.page_range %}
        {% if owner_page.number == n %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ n }}">{{ n }}<span class="sr-only">(current)</span></a>
        </li>
        {% elif n > owner_page.number|add:-3 and n < owner_page.number|add:3 %}
        <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
        {% endif %}
        {% endfor %}

        <li class="page-item {% if not next_owner_page_url %} disabled {% endif %}">
            <a class="page-link" href="{{ next_owner_page_url }}">Next</a>
        </li>
    </ul>
</nav>
{% endif %}
{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block header %}
<div class="p-2">
    <h4 align="center">Add a new post</h4>
</div>
{% endblock header %}

{% block content %}

<form action="{% url 'blogs:new_post' %}" class="form" enctype="multipart/form-data"
      method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-dark">Add post</button>
    {% endbuttons %}


</form>

{% endblock content %}

blogs/templates/blogs/new_tag.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block header %}
<div class="p-2">
    <h4 align="center">Add a new tag</h4>
</div>
{% endblock header %}

{% block content %}

<form action="{% url 'blogs:new_tag' %}" class="form"
      method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-dark">Add tag</button>
    {% endbuttons %}

    {% if tags %}
    <div class="p-2">
        <h4 align="center">Delete tag</h4>
    </div>
    {% endif %}
    <div class="card-group">
        {% for tag in tags %}
        <div class="col-md-2 p-1">
            <div class="card">
                <div class="card-body">
                    {{ tag.title }}
                    <div class="float-right">
                        <a href="{% url 'blogs:delete_tag' tag.id %}" class="btn btn-sm btn-outline-danger"
                           role="button">X</a>
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</form>

{% endblock content %}

blogs/templates/blogs/post_details.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block header %}

{% endblock header %}

{% block content %}

<div class="p-2">
    <div class="card mb-4">
        {% if post.image %}
        <img src="{{ post.image.url }}" class="card-img-top" alt="...">
        {% endif %}
        <div class="card-body">
            {% if post.owner.id == request.user.id %}
            {% if post.public %}
            <h5>
                {{ post.title|linebreaks }}
                <a href="{% url 'blogs:privat_public' post.id %}" class="badge badge-success">Public</a>
            </h5>
            {% else %}
            <h5>
                {{ post.title|linebreaks }}
                <a href="{% url 'blogs:privat_public' post.id %}" class="badge badge-dark">Private</a>
            </h5>
            {% endif %}
            {% else %}
            <h5 class="card-title">{{ post.title|linebreaks }}</h5>
            {% endif %}


            <p class="text-justify">{{ post.text|linebreaks }}</p>
            <p>
            <div class="card-footer">
                <h6 align="right">Author: {{ post.owner }}</h6>
                <small class="text-muted">Create: {{ post.date_added|date:'M d, Y H:i' }}</small>
                <small class="text-muted">Edit: {{ post.date_edit|date:'M d, Y H:i' }}</small>
                <small class="text-muted">Published: {{ post.date_publication|date:'M d, Y H:i' }}</small>
            </div>
            </p>
            {% if post.owner.id == request.user.id %}
            <p><a href="{% url 'blogs:edit_post' post.id %}" class="btn btn-outline-dark" role="button">Edit</a>
                <a href="{% url 'blogs:delete_post' post.id %}" class="btn btn-outline-danger" role="button">X</a></p>
            {% endif %}
            <a href="{% url 'blogs:index' %}" class="btn btn-outline-secondary btn-block" role="button">to public
                posts</a>
        </div>
    </div>
</div>
{% endblock content %}

blogs/templates/blogs/tag_detail.html
{% extends "blogs/base.html" %}

{% block header %}

<div class="pt-2">
    <h2 align="center">Posts with tag <b>{{ tag.title }}</b></h2>
</div>

{% endblock header %}

{% block content %}
<div class="card-group">
    {% for post in tag_page.object_list %}
    <div class="col-md-6 p-2">
        <div class="card">
            {% if post.image %}
            <img src="{{ post.image.url }}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ post.title|linebreaks }}</h5>
                {% if post.text|length > 500 %}
                <p class="text-justify">{{ post.text|truncatechars:500 }}</p>
                {% else %}
                <p class="text-justify">{{ post.text|linebreaks }}</p>
                {% endif %}
                <div class="pb-3">
                    Tags:
                    {% for tag in post.tags.all %}
                    <a href="{% url 'blogs:tag_detail' tag.id %}">
                        #{{ tag.title }}
                    </a>
                    {% empty %}
                    none
                    {% endfor %}
                </div>
                <p><a href="{% url 'blogs:post_details' post.id %}" class="btn btn-outline-dark btn-block"
                      role="button">Read</a></p>
                <div class="card-footer">
                    <div class="float-right">Author: {{ post.owner }}</div>
                    <small class="text-muted">{{ post.date_added|date:'M d, Y H:i' }} Create</small>
                    <br><small class="text-muted">{{ post.date_edit|date:'M d, Y H:i' }} Edit</small></br>
                    <small class="text-muted">{{ post.date_publication|date:'M d, Y H:i' }} Published</small>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    There are no posts in this category.
    {% endfor %}
</div>

{% if tag_posts|length > 10 %}
<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item {% if not prev_tag_page_url %} disabled {% endif %}">
            <a class="page-link" href="{{ prev_tag_page_url }}" tabindex="-1" aria-disabled="true">Previous</a>
        </li>

        {% for n in tag_page.paginator.page_range %}
        {% if tag_page.number == n %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ n }}">{{ n }}<span class="sr-only">(current)</span></a>
        </li>
        {% elif n > tag_page.number|add:-3 and n < tag_page.number|add:3 %}
        <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
        {% endif %}
        {% endfor %}

        <li class="page-item {% if not next_tag_page_url %} disabled {% endif %}">
            <a class="page-link" href="{{ next_tag_page_url }}">Next</a>
        </li>
    </ul>
</nav>
{% endif %}

{% endblock %}